-- MySQL Script generated by MySQL Workbench
-- 07/05/17 10:07:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_classroom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_classroom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_classroom` DEFAULT CHARACTER SET utf8 ;
USE `db_classroom` ;

-- -----------------------------------------------------
-- Table `db_classroom`.`classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_classroom`.`classroom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(8) NOT NULL DEFAULT '',
  `capacity` INT NOT NULL DEFAULT 0,
  `extra` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_classroom`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_classroom`.`teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(8) NOT NULL DEFAULT '',
  `course` VARCHAR(45) NOT NULL DEFAULT '',
  `career_title` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_classroom`.`hire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_classroom`.`hire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `classroom_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hire_classroom1_idx` (`classroom_id` ASC),
  INDEX `fk_hire_teacher1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_hire_classroom1`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `db_classroom`.`classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hire_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `db_classroom`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_classroom`.`day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_classroom`.`day` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hire_id` INT NOT NULL,
  `day` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_day_hire1_idx` (`hire_id` ASC),
  CONSTRAINT `fk_day_hire1`
    FOREIGN KEY (`hire_id`)
    REFERENCES `db_classroom`.`hire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_classroom`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_classroom`.`time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day_id` INT NOT NULL,
  `start_time` INT NOT NULL DEFAULT 0,
  `duration` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_time_day1_idx` (`day_id` ASC),
  CONSTRAINT `fk_time_day1`
    FOREIGN KEY (`day_id`)
    REFERENCES `db_classroom`.`day` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
